connections {
    vista-cbc {
        version = 2
        proposals = aes256-sha256-modp2048

        local_addrs  = 172.20.0.10
        remote_addrs = 172.20.0.2

        local {
            auth = psk
            id   = vista-gateway
        }

        remote {
            auth = psk
            id   = vista-client
        }

        children {
            vista-cbc-child {
                local_ts  = 172.20.0.10/32
                remote_ts = 172.20.0.2/32
                mode      = transport

                esp_proposals = aes256-sha256-modp2048

                start_action = trap
                close_action = trap
            }
        }
    }
}

secrets {
    ike-vista {
        id-1   = vista-gateway
        id-2   = vista-client
        secret = "VISTA-SIH-2026-PSK"
    }
}
