connections {
    vista-duplex {
        version = 2
        proposals = aes256-sha256-modp2048

        local_addrs = 172.20.0.10
        remote_addrs = 172.20.0.2

        local {
            auth = psk
            id = pc2
        }

        remote {
            auth = psk
            id = pc1
        }

        children {
            pc-duplex {
                local_ts = 172.20.0.10/32
                remote_ts = 172.20.0.2/32
                mode = transport
                esp_proposals = aes256gcm128-aes256-sha256-modp2048
                start_action = trap
                close_action = trap
            }
        }
    }
}

secrets {
    ike-vista {
        id-1 = pc2
        id-2 = pc1
        secret = "VISTA-SIH-2026-PSK"
    }
}
