connections {
    pc1-pc2 {
        version = 2
        proposals = aes256-sha256-modp2048

        local_addrs = 172.20.0.2
        remote_addrs = 172.20.0.3

        local {
            auth = psk
            id = pc1
        }

        remote {
            auth = psk
            id = pc2
        }

        children {
            pc-tunnel {
                local_ts = 172.20.0.2/32
                remote_ts = 172.20.0.3/32
                mode = tunnel
                esp_proposals = aes256-sha256-modp2048
                start_action = none
                close_action = trap
            }
        }
    }
}

secrets {
    ike-pc1-pc2 {
        id-1 = pc1
        id-2 = pc2
        secret = "VISTA-SIH-2026-PSK"
    }
}
